defaults: &defaults
  help_page_url: "http://www.railstutorial.org/help"
  book_url: "http://www.railstutorial.org/book"

user:
  max_name_length: 50
  max_email_length: 255
  hundred_years: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
